### ISSUE TITLE
Bug on new schema change to CondaPackage database sqlalchemy table

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#128]
Making a request to `api/v1/package/` currently fails on `main`. Using python's `requests` library, you can do

```python
import requests
requests.get('http://localhost:5000/api/v1/package/')
```

And the response I get is 500. Here's the log:

```
postgres_1            | 2021-09-15 20:45:22.645 UTC [55] ERROR:  column conda_package.summary does not exist at character 730
postgres_1            | 2021-09-15 20:45:22.645 UTC [55] STATEMENT:  SELECT conda_package.id AS conda_package_id, conda_package.channel_id AS conda_package_channel_id, conda_package.build AS conda_package_build, conda_package.build_number AS conda_package_build_number, conda_package.constrains AS conda_package_constrains, conda_package.depends AS conda_package_depends, conda_package.license AS conda_package_license, conda_package.license_family AS conda_package_license_family, conda_package.md5 AS conda_package_md5, conda_package.name AS conda_package_name, conda_package.sha256 AS conda_package_sha256, conda_package.size AS conda_package_size, conda_package.subdir AS conda_package_subdir, conda_package.timestamp AS conda_package_timestamp, conda_package.version AS conda_package_version, conda_package.summary AS conda_package_summary, conda_package.description AS conda_package_description 
postgres_1            | 	FROM conda_package 
postgres_1            | 	LIMIT 100 OFFSET 0
conda-store-server_1  | 172.18.0.1 - - [15/Sep/2021 20:45:22] "GET /api/v1/package/ HTTP/1.1" 500 -
conda-store-server_1  | Traceback (most recent call last):
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
conda-store-server_1  |     self.dialect.do_execute(
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
conda-store-server_1  |     cursor.execute(statement, parameters)
conda-store-server_1  | psycopg2.errors.UndefinedColumn: column conda_package.summary does not exist
conda-store-server_1  | LINE 1: ..., conda_package.version AS conda_package_version, conda_pack...
conda-store-server_1  |                                                              ^
conda-store-server_1  | 
conda-store-server_1  | The above exception was the direct cause of the following exception:
conda-store-server_1  | 
conda-store-server_1  | Traceback (most recent call last):
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 2088, in __call__
conda-store-server_1  |     return self.wsgi_app(environ, start_response)
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
conda-store-server_1  |     response = self.handle_exception(e)
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
conda-store-server_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
conda-store-server_1  |     response = self.full_dispatch_request()
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
conda-store-server_1  |     rv = self.handle_user_exception(e)
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
conda-store-server_1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
conda-store-server_1  |     rv = self.dispatch_request()
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
conda-store-server_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
conda-store-server_1  |   File "/opt/conda-store-server/conda_store_server/server/views/api.py", line 226, in api_list_packages
conda-store-server_1  |     return paginated_api_response(orm_packages, schema.CondaPackage, limit, offset)
conda-store-server_1  |   File "/opt/conda-store-server/conda_store_server/server/views/api.py", line 29, in paginated_api_response
conda-store-server_1  |     for _ in query.limit(limit).offset(offset).all()
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2711, in all
conda-store-server_1  |     return self._iter().all()
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
conda-store-server_1  |     result = self.session.execute(
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
conda-store-server_1  |     result = conn._execute_20(statement, params or {}, execution_options)
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
conda-store-server_1  |     return meth(self, args_10style, kwargs_10style, execution_options)
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
conda-store-server_1  |     return connection._execute_clauseelement(
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
conda-store-server_1  |     ret = self._execute_context(
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
conda-store-server_1  |     self._handle_dbapi_exception(
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
conda-store-server_1  |     util.raise_(
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
conda-store-server_1  |     raise exception
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
conda-store-server_1  |     self.dialect.do_execute(
conda-store-server_1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
conda-store-server_1  |     cursor.execute(statement, parameters)
conda-store-server_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column conda_package.summary does not exist
conda-store-server_1  | LINE 1: ..., conda_package.version AS conda_package_version, conda_pack...
conda-store-server_1  |                                                              ^
conda-store-server_1  | 
conda-store-server_1  | [SQL: SELECT conda_package.id AS conda_package_id, conda_package.channel_id AS conda_package_channel_id, conda_package.build AS conda_package_build, conda_package.build_number AS conda_package_build_number, conda_package.constrains AS conda_package_constrains, conda_package.depends AS conda_package_depends, conda_package.license AS conda_package_license, conda_package.license_family AS conda_package_license_family, conda_package.md5 AS conda_package_md5, conda_package.name AS conda_package_name, conda_package.sha256 AS conda_package_sha256, conda_package.size AS conda_package_size, conda_package.subdir AS conda_package_subdir, conda_package.timestamp AS conda_package_timestamp, conda_package.version AS conda_package_version, conda_package.summary AS conda_package_summary, conda_package.description AS conda_package_description 
conda-store-server_1  | FROM conda_package 
conda-store-server_1  |  LIMIT %(param_1)s OFFSET %(param_2)s]
conda-store-server_1  | [parameters: {'param_1': 100, 'param_2': 0}]
conda-store-server_1  | (Background on this error at: https://sqlalche.me/e/14/f405)
```

I should note that I'm running conda-store inside a docker container, using `examples/docker/docker-compose.yml`. Inside that directory, I did `docker-compose up --build` to get conda-store running.

This appears to be affecting `api/v1/environment/` as well, as that endpoint fetches package data for each environment.

**Comment by costrouc** [comment]
@peytondmurray currently I don't have any database migration tool e.g. like [alembic](https://alembic.sqlalchemy.org/en/latest/) and a few others. My guess is that the postgres database is being preserved and the tables have not updated properly leading to this error due to me changing the schema recently. There is no way we will have a migration tool working in this short time. Possibly a future feature we need to add as conda-store become more popular.

For now I would recommend `docker-compose down` and then `docker-compose up --build`. You will also need to delete the `data` directory that was created in `examples/docker`.

Let me know if this fixes the problem.

**Comment by peytondmurray** [comment]
@costrouc Thanks, that was totally it - closing this issue as resolved.
