### ISSUE TITLE
Cannot modify environments through the API

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#202]
## Problem
When I POST a specification for a brand new namespace+environment to `/api/v1/specification/`, the conda-store server happily creates a new environment. However, when I POST a specification with different dependencies for an existing namespace+environment, the conda-store server responds with a `403 FORBIDDEN`.

## My environment

I'm running conda-store server with docker, using `examples/docker/docker-compose.yaml`. I have modified my `conda_store_config.py` to include the line
```
...
c.RBACAuthorizationBackend.unauthenticated_role_bindings = {
    "*/*": {"admin"}
}
...
```
to give permissions to anybody for any endpoint.

## What I've tried
After speaking with @costrouc I think this has something to do with being authorized but not authenticated. When I POST to `/api/v1/specification/`, the request gets authorized here: https://github.com/Quansight/conda-store/blob/12310549d344c11e224b37ea400f0db5400bc213/conda-store-server/conda_store_server/server/views/api.py#L274

I added some logging to `authorize_request` to try to understand why the request succeeds when I'm creating a new environment but fails when I try to modify an existing environment:

```python
    def authorize_request(self, arn, permissions, require=False):
        if not hasattr(g, "entity"):
            self.authenticate_request()

        if not hasattr(g, "authorized"):
            role_bindings = {} if (g.entity is None) else g.entity.role_bindings
            g.authorized = self.authorization.authorize(
                role_bindings, arn, permissions, g.entity is not None
            )
            self.log.warn(f'role_bindings={role_bindings}, permissions={permissions}, g.authorized={g.authorized}')

        self.log.warn(f'g.entity={getattr(g, "entity", "")}, g.authorized={getattr(g, "authorized", "")}')
        if require and not g.authorized:
            response = jsonify({"status": "error", "message": "request not authorized"})
            response.status_code = 403
            abort(response)

        return g.authorized
```

With this extra logging enabled, I tried deleting a package from an existing environment:
```
docker-conda-store-server-1  | 172.22.0.1 - - [09/Nov/2021 02:40:19] "OPTIONS /api/v1/specification/ HTTP/1.1" 200 -
docker-conda-store-server-1  | [CondaStoreServer] WARNING | role_bindings={}, permissions={<Permissions.ENVIRONMENT_CREATE: 'environment:create'>}, g.authorized=False
docker-conda-store-server-1  | [CondaStoreServer] WARNING | g.entity=None, g.authorized=False
docker-conda-store-server-1  | 172.22.0.1 - - [09/Nov/2021 02:40:19] "POST /api/v1/specification/ HTTP/1.1" 403 -
```

And here's what it looks like when creating a brand new environment:

```
docker-conda-store-server-1  | 172.22.0.1 - - [09/Nov/2021 02:43:30] "OPTIONS /api/v1/specification/ HTTP/1.1" 200 -
docker-conda-store-server-1  | [CondaStoreServer] WARNING | role_bindings={}, permissions={<Permissions.ENVIRONMENT_CREATE: 'environment:create'>, <Permissions.NAMESPACE_CREATE: 'namespace::create'>}, g.authorized=True
docker-conda-store-server-1  | [CondaStoreServer] WARNING | g.entity=None, g.authorized=True
docker-conda-store-server-1  | [CondaStoreServer] specification name=wooo sha256=487beebb00b43955ba43f9cd3d706c97743dd0c0966f3172608739c1911e864f registered
docker-conda-store-server-1  | 172.22.0.1 - - [09/Nov/2021 02:43:31] "POST /api/v1/specification/ HTTP/1.1" 200 -
```

As you can see `g.authorized` is different for the two cases. I've tried setting https://github.com/Quansight/conda-store/blob/12310549d344c11e224b37ea400f0db5400bc213/conda-store-server/conda_store_server/server/views/api.py#L277 to `False` and that seems to fix the problem, but I'd be really grateful if someone who knows more about conda-store's permissions could weigh in here to help me understand why this is the case.

**Comment by costrouc** [comment]
Was able to reproduce this with a fetch request

```javascript
fetch('http://localhost:5000/api/v1/specification/', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({namespace: 'default', specification: JSON.stringify({name: 'qwer', dependencies: ['flask']})})})
```

**Comment by peytondmurray** [comment]
After testing on 4db34b7 it seems there's a new bug introduced when trying to create an environment in any namespace that isn't `default`. Here's the log when I try to create a new environment `def` inside namespace `abc`:

```
docker-conda-store-server-1  | 172.18.0.1 - - [12/Nov/2021 22:58:22] "POST /api/v1/specification/ HTTP/1.1" 500 -
docker-conda-store-server-1  | Traceback (most recent call last):
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
docker-conda-store-server-1  |     return self.wsgi_app(environ, start_response)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
docker-conda-store-server-1  |     response = self.handle_exception(e)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
docker-conda-store-server-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
docker-conda-store-server-1  |     response = self.full_dispatch_request()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
docker-conda-store-server-1  |     rv = self.handle_user_exception(e)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
docker-conda-store-server-1  |     return cors_after_request(app.make_response(f(*args, **kwargs)))
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
docker-conda-store-server-1  |     rv = self.dispatch_request()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
docker-conda-store-server-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
docker-conda-store-server-1  |   File "/opt/conda-store-server/conda_store_server/server/views/api.py", line 275, in api_post_specification
docker-conda-store-server-1  |     f"{namespace.name}/{specification.name}",
docker-conda-store-server-1  | AttributeError: 'NoneType' object has no attribute 'name'
```
