### ISSUE TITLE
Role "postgres" does not exist

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/conda-store#318]
I just cloned conda-store @ 0083077, ran `docker compose up --build` inside `conda-store/examples/docker` and got the following message about the `postgres` role not existing:

```
docker-postgres-1            | 2022-06-08 19:56:28.863 UTC [28] FATAL:  password authentication failed for user "postgres"
docker-postgres-1            | 2022-06-08 19:56:28.863 UTC [28] DETAIL:  Role "postgres" does not exist.
docker-postgres-1            | 	Connection matched pg_hba.conf line 99: "host all all all md5"
docker-conda-store-server-1  | Traceback (most recent call last):
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
docker-conda-store-server-1  |     return fn()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 310, in connect
docker-conda-store-server-1  |     return _ConnectionFairy._checkout(self)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
docker-conda-store-server-1  |     fairy = _ConnectionRecord.checkout(pool)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
docker-conda-store-server-1  |     rec = pool._do_get()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
docker-conda-store-server-1  |     return self._create_connection()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
docker-conda-store-server-1  |     return _ConnectionRecord(self)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
docker-conda-store-server-1  |     self.__connect()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
docker-conda-store-server-1  |     with util.safe_reraise():
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
docker-conda-store-server-1  |     compat.raise_(
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
docker-conda-store-server-1  |     raise exception
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
docker-conda-store-server-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 590, in connect
docker-conda-store-server-1  |     return dialect.connect(*cargs, **cparams)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
docker-conda-store-server-1  |     return self.dbapi.connect(*cargs, **cparams)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
docker-conda-store-server-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-conda-store-server-1  | psycopg2.OperationalError: connection to server at "postgres" (172.18.0.6), port 5432 failed: FATAL:  password authentication failed for user "postgres"
docker-conda-store-server-1  | 
docker-conda-store-server-1  | 
docker-conda-store-server-1  | The above exception was the direct cause of the following exception:
docker-conda-store-server-1  | 
docker-conda-store-server-1  | Traceback (most recent call last):
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/bin/conda-store-server", line 33, in <module>
docker-conda-store-server-1  |     sys.exit(load_entry_point('conda-store-server', 'console_scripts', 'conda-store-server')())
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/traitlets/config/application.py", line 976, in launch_instance
docker-conda-store-server-1  |     app.start()
docker-conda-store-server-1  |   File "/opt/conda-store-server/conda_store_server/server/app.py", line 213, in start
docker-conda-store-server-1  |     self.conda_store.ensure_namespace()
docker-conda-store-server-1  |   File "/opt/conda-store-server/conda_store_server/app.py", line 342, in ensure_namespace
docker-conda-store-server-1  |     namespace = api.get_namespace(self.db, name=self.default_namespace)
docker-conda-store-server-1  |   File "/opt/conda-store-server/conda_store_server/app.py", line 279, in db
docker-conda-store-server-1  |     return self.session_factory()
docker-conda-store-server-1  |   File "/opt/conda-store-server/conda_store_server/app.py", line 269, in session_factory
docker-conda-store-server-1  |     self._session_factory = orm.new_session_factory(
docker-conda-store-server-1  |   File "/opt/conda-store-server/conda_store_server/orm.py", line 422, in new_session_factory
docker-conda-store-server-1  |     Base.metadata.create_all(engine)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4888, in create_all
docker-conda-store-server-1  |     bind._run_ddl_visitor(
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3146, in _run_ddl_visitor
docker-conda-store-server-1  |     with self.begin() as conn:
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3062, in begin
docker-conda-store-server-1  |     conn = self.connect(close_with_result=close_with_result)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
docker-conda-store-server-1  |     return self._connection_cls(self, close_with_result=close_with_result)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
docker-conda-store-server-1  |     else engine.raw_connection()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
docker-mysql-1               | 
docker-conda-store-server-1  |     return self._wrap_pool_connect(self.pool.connect, _connection)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3283, in _wrap_pool_connect
docker-mysql-1               | 2022-06-08 19:56:28+00:00 [Note] [Entrypoint]: Stopping temporary server
docker-conda-store-server-1  |     Connection._handle_dbapi_exception_noconnection(
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2117, in _handle_dbapi_exception_noconnection
docker-conda-store-server-1  |     util.raise_(
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
docker-conda-store-server-1  |     raise exception
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
docker-conda-store-server-1  |     return fn()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 310, in connect
docker-conda-store-server-1  |     return _ConnectionFairy._checkout(self)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
docker-conda-store-server-1  |     fairy = _ConnectionRecord.checkout(pool)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
docker-conda-store-server-1  |     rec = pool._do_get()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
docker-conda-store-server-1  |     return self._create_connection()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
docker-conda-store-server-1  |     return _ConnectionRecord(self)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
docker-conda-store-server-1  |     self.__connect()
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 665, in __connect
docker-conda-store-server-1  |     with util.safe_reraise():
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
docker-conda-store-server-1  |     compat.raise_(
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
docker-conda-store-server-1  |     raise exception
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
docker-conda-store-server-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 590, in connect
docker-conda-store-server-1  |     return dialect.connect(*cargs, **cparams)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 597, in connect
docker-conda-store-server-1  |     return self.dbapi.connect(*cargs, **cparams)
docker-conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
docker-conda-store-server-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
docker-conda-store-server-1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "postgres" (172.18.0.6), port 5432 failed: FATAL:  password authentication failed for user "postgres"
docker-conda-store-server-1  | 
docker-conda-store-server-1  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
docker-mysql-1               | 2022-06-08T19:56:28.882935Z 13 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.29).
docker-conda-store-server-1 exited with code 1
docker-mysql-1               | 2022-06-08T19:56:31.113404Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.29)  MySQL Community Server - GPL.
docker-mysql-1               | 2022-06-08 19:56:31+00:00 [Note] [Entrypoint]: Temporary server stopped
docker-mysql-1               | 
docker-mysql-1               | 2022-06-08 19:56:31+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
docker-mysql-1               | 
docker-mysql-1               | 2022-06-08T19:56:32.168268Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 1
docker-mysql-1               | 2022-06-08T19:56:32.185558Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
docker-mysql-1               | 2022-06-08T19:56:32.463988Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
docker-mysql-1               | 2022-06-08T19:56:32.797915Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
docker-mysql-1               | 2022-06-08T19:56:32.798064Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
docker-mysql-1               | 2022-06-08T19:56:32.802909Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
docker-mysql-1               | 2022-06-08T19:56:32.857573Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
docker-mysql-1               | 2022-06-08T19:56:32.857714Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
ocker-postgres-1            | 2022-06-08 19:56:35.997 UTC [36] FATAL:  role "postgres" does not exist
docker-jupyterhub-1          | [I 2022-06-08 19:56:36.404 JupyterHub log:189] 200 GET /hub/api/ (@127.0.0.1) 1.45ms
[last two messages repeat ad infinitum]
```

**Comment by peytondmurray** [comment]
Okay, it looks like a `POSTGRES_USER` environment variable needs to be set [in order to create a superuser in the docker container](https://hub.docker.com/_/postgres). Making a PR now.
