### ISSUE TITLE
Error when fetching base image from docker hub

### ISSUE THREAD

**Issue by costrouc** [Quansight/conda-store#37]
```python
Traceback (most recent call last):

  File "/opt/conda-store/conda_store/build.py", line 210, in conda_build

    build_docker_image(conda_store, build_path, build)

  File "/opt/conda-store/conda_store/build.py", line 263, in build_docker_image

    image = build_docker_environment_image(

  File "/opt/conda/envs/conda-store/lib/python3.9/site-packages/conda_docker/conda.py", line 631, in build_docker_environment_image

    image = pull_image(base_image_name, base_image_tag)

  File "/opt/conda/envs/conda-store/lib/python3.9/site-packages/conda_docker/registry/client.py", line 46, in pull_image

    digest = get_blob(image, blob["blobSum"], token)

  File "/opt/conda/envs/conda-store/lib/python3.9/site-packages/conda_docker/registry/client.py", line 36, in get_blob

    return gzip.decompress(get_request(url, headers))

  File "/opt/conda/envs/conda-store/lib/python3.9/site-packages/conda_docker/registry/client.py", line 17, in get_request

    return urlopen(request).read()

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 214, in urlopen

    return opener.open(url, data, timeout)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 523, in open

    response = meth(req, response)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 632, in http_response

    response = self.parent.error(

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 555, in error

    result = self._call_chain(*args)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 494, in _call_chain

    result = func(*args)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 747, in http_error_302

    return self.parent.open(new, timeout=req.timeout)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 523, in open

    response = meth(req, response)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 632, in http_response

    response = self.parent.error(

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 561, in error

    return self._call_chain(*args)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 494, in _call_chain

    result = func(*args)

  File "/opt/conda/envs/conda-store/lib/python3.9/urllib/request.py", line 641, in http_error_default

    raise HTTPError(req.full_url, code, msg, hdrs, fp)

urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by costrouc** [comment]
Depends on https://github.com/conda-incubator/conda-docker/issues/12

**Comment by costrouc** [comment]
Closing since fixed in https://github.com/conda-incubator/conda-docker/issues/12
